version: "3.9"

services:
  tiq-web:
    build: .
    container_name: tiq-web
    restart: unless-stopped
    environment: 
      - VIRTUAL_HOST=illuminati.mec.ac.in
      - VIRTUAL_PORT=3000
    
    networks:
      default:
        external:
          name: mec
          